### ISSUE TITLE
FYI: ALE support for (Neo)Vim available

### ISSUE THREAD

**Issue by oblitum** [cleishm/libcypher-parser#10]
For your information, I made the linter available in [ALE](https://github.com/w0rp/ale), so anyone that uses ALE with Vim or NeoVim and have `cypher-lint` in path will benefit from instant lint feedback while editing Cypher source files.

**Comment by cleishm** [comment]
That's awesome! Thanks!

If you send a PR updating the README to mention this, I'd be happy to merge it.

**Comment by oblitum** [comment]
Done ;)
