### ISSUE TITLE
Operators precedency 

### ISSUE THREAD

**Issue by DvirDukhan** [cleishm/libcypher-parser#15]
Hi
There might be an issue with operators precedence, given an "IN" operator and subscript operator.
Given [this open cypher TCK scenario](https://github.com/opencypher/openCypher/blob/18fc8baccb6ed4f2ccf08dd684c1566eaccbc648/tck/features/ListOperations.feature#L47), the query is 
`RETURN 3 IN [[1, 2, 3]][0] AS r`, which should return true.

The AST generated by libcypher-parser is as follows:
![Screen Shot 2019-08-05 at 10 24 38](https://user-images.githubusercontent.com/12258836/62446422-58c1f280-b76b-11e9-9e07-1708956c636b.png)

I believe that the "IN" operator should be the higher in the tree, while the subscript should be much lower

**Comment by cleishm** [comment]
Hi @DvirDukhan!

Thanks for reporting this. I agree it looks wrong.

`libcypher-parser` uses a precedence-climbing algorithm for operator parsing, which is more accurate and simpler than the implementation in Neo4j itself (and in the opencypher example grammar). Each operator's precedence is defined numerically, in [operators.c](https://github.com/cleishm/libcypher-parser/blob/v0.6.2/lib/src/operators.c). Currently, both subscripts and the `IN` binary operator have a precedence level of 11 - hence it is parsing in order of appearance. This should be trivial to adjust.

Would you be interested in adding a test case for this and then adjusting the precedence levels to make it parse correctly?

Cheers,
Chris

**Comment by DvirDukhan** [comment]
Hi @cleishm 
I'll open a PR for that.
I will appreciate your guidance in integrating with your test suite.
Will decreasing the precedence of the subscript operator is correct in the cypher grammar?

**Comment by cleishm** [comment]
The tests for expression parsing are in https://github.com/cleishm/libcypher-parser/blob/v0.6.2/lib/test/check_expression.c. You could add a test here for this case.

**Comment by cleishm** [comment]
> Is changing the precedence of the subscript operator to 12 is correct in the cypher grammar?

You likely want to review all the operators at precedence levels 11 and 12. Map expressions (`l{e}`) should probably also bind closer than `IN` (and others at level 11).

**Comment by cleishm** [comment]
Closed by #16
