### ISSUE TITLE
Version for conditional compilation

### ISSUE THREAD

**Issue by franekp** [cleishm/libcypher-parser#2]
Could you expose the version numbers as a #define macros? (example: https://github.com/python/cpython/blob/master/Include/patchlevel.h)
This way users would be able to write code that works with different versions of the library.

**Comment by cleishm** [comment]
Hey @franekp!

Sounds like a good idea. Any chance you could make a PR for it?

Cheers,
Chris

**Comment by cleishm** [comment]
I think 5dcade8 resolves it?

**Comment by franekp** [comment]
Yes, this resolves it. Thank you.
