### ISSUE TITLE
Accepting Binary Inputs

### ISSUE THREAD

**Issue by victorstewart** [cleishm/libcypher-parser#30]
I'm using RedisGraph and implementing some custom graph algorithms, and was hoping I'd be able to pass a serialized binary blob into my functions, so that I receive my inputs pre-structured and avoid having to parse them.

Something like... `CALL algo.abc(binaryBlob)`

This of course isn't possible because cypher relies on string parsing. But maybe you have some other suggestion for me to accomplish this?

**Comment by cleishm** [comment]
This would be a concern for the cypher language itself. In general, you'd probably accomplish this by using query parameters.
