### ISSUE TITLE
A question regarding numbers representation

### ISSUE THREAD

**Issue by DvirDukhan** [cleishm/libcypher-parser#34]
Hi
Can you please explain the considerations for allowing a number (integer or float) representation to be only a string representing only non-negative values, while negative values are expressions with unary minus operation over a non-negative number?
```
float-string =
      < [0-9]+ '.'? [0-9]* [eE] [-+]? [0-9] sym-part* >
                                       { strbuf_append_block(); }
    | < [0-9]* '.' [0-9] sym-part* >   { strbuf_append_block(); }

integer-string = < [0-9] sym-part* >   { strbuf_append_block(); }
```
Your answer is appreciated.

**Comment by cleishm** [comment]
Otherwise, it becomes ambiguous in the grammar.
