### ISSUE TITLE
libcypher-parser allows clause sequences prohibited by the grammar

### ISSUE THREAD

**Issue by jeffreylovitz** [cleishm/libcypher-parser#37]
Cypher has some restrictions in its grammar file regarding clause sequences. For example, in a single-part query, a reading clause cannot follow a writing clause, and no clause can follow `RETURN`.

libcypher-parser allows these constructions, however, constructing ASTs for queries such as:
```
CREATE (a) MATCH (a)
RETURN 1 DELETE a
RETURN 1 RETURN 1
```

Shouldn't these constructions trigger parser errors?

**Comment by cleishm** [comment]
I'd say they are semantic errors rather than parse errors. Adding a semantic checker to libcypher-parser has been a long held desire.
