### ISSUE TITLE
cmake build issue when running `tests`

### ISSUE THREAD

**Issue by chakpongchung** [cleishm/libcypher-parser#43]
libcypher-parser/lib/test/check_libcypher-parser_suite.c:1:10: fatal error: check.h: No such file or directory
    1 | #include <check.h>
      |          ^~~~~~~~~

https://stackoverflow.com/questions/63697460/installed-check-for-c-but-check-h-not-found

I saw this post. Do I need to add any cmake arguments to get this working? I installed `check` by `sudo apt install check`.

I have this in the CMakeList.txt:

```
SET(CMAKE_C_FLAGS "-lpthread -lX11 -ldrm -lcheck -lm  -lrt -lsubunit")

```
Thank you in advance!

**Comment by cleishm** [comment]
I don't use cmake, but rather the autotools suite (`./configure` et al), so I can't help here. Perhaps someone else can.
