### ISSUE TITLE
Can we use the latest openCypher grammar to generate the libcypher-parser with PEG/LEG?

### ISSUE THREAD

**Issue by chakpongchung** [cleishm/libcypher-parser#44]
I have seen a lot of incorrect behaviors when parsing queries from LDBC and TCK .

@cleishm @Loupi @jeffreylovitz @DvirDukhan

**Comment by cleishm** [comment]
There is no automated way to do that. Feel free to submit PRs to fix each case you find divergence, or at least open an issue and hopefully someone will take up the work.
