### ISSUE TITLE
Linting a composite index CREATE statement fails unexpectedly

### ISSUE THREAD

**Issue by petebaker-pge** [cleishm/libcypher-parser#6]
Creating a file `point.cypher` with the contents:

```
create index on :Point(latitude, longitude);
```

and running

```
$ cypher-lint point.cypher
```

gets the following result:

```
point.cypher:1:32: Invalid input ',': expected ')'
create index on :Point(latitude, longitude);
                               ^
```

I expected this statement to lint correctly, per the spec here: https://neo4j.com/docs/developer-manual/current/cypher/schema/index/#create-a-composite-index

Are composite index statements not supported by the linter?

**Comment by cleishm** [comment]
Seems likely it’s not (yet). Neo occasionally add things ahead of official support in opencypher. I’m guessing that’s the case here.

Shouldn’t be hard to add. Anyone want to take that on?
