### ISSUE TITLE
Build error on GCC 8.2.1 (20180831) due to -Werror

### ISSUE THREAD

**Issue by oblitum** [cleishm/libcypher-parser#8]
On ArchLinux, the current system's default GCC won't build the code because of a warning that's treated as error. Personally, I'm against releasing code to end users with -Werror, it makes sense on author's testing grid, but not on myriad end user's configurations. Warnings can vary per compiler and per compiler version. Sorry, that's the reason I'm reporting the occurrence without disclosing the error. If it had been kept as a warning I'd probably report and disclose it instead.

**Comment by cleishm** [comment]
I'd still prefer to fix the warnings, as they can often point to real issues.

What about we set up some kind of CI that runs the build (& tests) on a variety of platforms? I'd be happy to let you take that on. When we've got that, we can probably remove the default `-Werror` and make it an option that is used in CI/development?

**Comment by oblitum** [comment]
> I'd still prefer to fix the warnings, as they can often point to real issues.

That's my position as well (though this particular case doesn't seem like a real issue).

> What about we set up some kind of CI that runs the build (& tests) on a variety of platforms? I'd be happy to let you take that on. When we've got that, we can probably remove the default -Werror and make it an option that is used in CI/development?

Possibly it's more prone to fail due to compiler type and version than the actual platform.

It's not because that such build/test grid is an unaccomplished author's wish that necessarily they should implicitly turn final user's machines into an improvised build/test grid. If it's the author's intention to do so, in respect to users, it should be at least explicitly stated in README (and/or after a failed build due to `-Werror`) that having the software built for their own use is secondary and it's more important that a user's build step be used for reporting back failures as part of virtual p2p CI system that they now have become part of. Despite their original intentions of reportings warnings in the build process (or pull requests to fix them) even if they weren't turned into errors.

**Comment by oblitum** [comment]
Another route, in respect to users, is to disclose the build was tailored for the author's CI, not particularly for user's machines, hence `-Werror`.

**Comment by oblitum** [comment]
I've noticed now that was covered in 7a858e0, so great.

By the way, thanks for the software. Sorry if this report was offensive in any sense, it was not my intention.
